### ISSUE TITLE
psdler xcfye cevrilecek 

### ISSUE THREAD

**Issue by NikosEfthias** [Gnu-linux-turkiye/linuxtr-tasarimlar#2]
adobe un psd formati linux uyumlu xcf formatina cevrilecek

**Comment by betul** [comment]
gimp üzerinden .xcf e dönüştürüldü

**Comment by NikosEfthias** [comment]
lfs track yapiliyor mu butun dosyalar sadece psd ya da jpg degil ? @betul

**Comment by betul** [comment]
xcf için denedim de oldu galiba.

**Comment by NikosEfthias** [comment]
clonelayacagim birazdan test edecegim o zamana kadar acik tutuyorum issue yu
